[icons]
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
vlc = "ï€½"
Chromium-browser = "ï‰¨"
firefox-nightly = "ï‰©"
Alacritty = "ï„ "
wezterm = "ï„ "
kitty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Nautilus = "ğŸ“˜"
Thunar = "ğŸ“˜"
Evince = "ï‡"
discord = "ï’"
Pavucontrol = "ï€"

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"
"org.wezfurlong.wezterm" = "wezterm"

[general]
wm_property = "class"

[options]
remove_duplicates = true
no_names = false
no_icon_names = true
