[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Chromium-browser = "ï‰¨"
firefox-nightly = "ï‰©"
Alacritty = "ï„ "
kitty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Nautilus = "ğŸ“˜"
Evince = "ï‡"
discord = "ï’"
Pavucontrol = "ï€"
# smile emoji

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = " î‚± "
wm_property = "class"

[options]
remove_duplicates = false
no_names = false
no_icon_names = true
